package ExceptionExample;

public class ExeptionExample {

    public static void main(String[] args) {

        Child c = new Child();

        c.message();

//        try {
//            int a[] = new int[5];
//            a[5] = 30/0;
//        } catch(ArithmeticException ae) {
//            System.out.println("ae: " + ae.getMessage());
//        } catch(ArrayIndexOutOfBoundsException aiob) {
//            System.out.println("aiob: " + aiob.getMessage());
//        } catch(Exception e) {
//            System.out.println("e: " + e.getMessage());
//        } finally {
//            System.out.println("finally");
//        }

//
//        int b = arr[5];
//
//        String str1 = "asd";
//
//        Integer a1 = Integer.parseInt(str1);
//
//        System.out.println(a1);
//
//        String str = null;
//
//        System.out.println("str.length() = " + str.length());

//        int a = 10;
//        try {
//            int d = a / 0;
//            System.out.println(d);
//        } catch(ArithmeticException ae) {
//            System.out.println(ae.getMessage());
//        } finally {
//            System.out.println("finally block");
//        }


    }
}
